### ISSUE TITLE
Issue when i run 'node server.js' 

### ISSUE THREAD

**Issue by cumakeway** [goodheads/yourtube#15]
I am getting an error when i run 'node server.js' . Below is my complete error stack. 

λ node server.js
{ [Error: ENOENT: no such file or directory, open 'C:\NodeProjects\yourtube.env']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\NodeProjects\yourtube\.env' }
module.js:327
    throw err;
    ^

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\NodeProjects\yourtube\server\models\user.server.model.js:2:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\NodeProjects\yourtube\server\controllers\user.server.controller.js:1:81)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by unicodeveloper** [comment]
You need to create a `.env` file in your root directory. Please re-read the README and follow the steps highlighted. Thanks 😊
